configuration:
  swagger:
    app: 'Gym management'
    description: 'Gym manegement system'
    developer: 'Kerim Sabic'
    email: 'kerim.sabic@stu.ibu.edu.ba'

  mailsender:
    default: 'mailgun'


azure:
  blob:
    service-endpoint:
    sas-token:
    container-name:


stripe:
  APIKEY:


spring:
  cloud:
    azure:
      storage:
        blob:


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

  data:
    mongodb:
      uri: mongodb+srv://kerimsabic2:sifra@gym.f9lt0t2.mongodb.net/?retryWrites=true&w=majority
      database: gym
  mail:
    host: smtp.gmail.com
    port: 587
    username: tesingtesting4@gmail.com
    password: 'ecvb elqo mrwp avtg'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
security:
  jwt:
    secret: 'YCgqRZm6TuGfqyl3n8NJWZU29pSQxklzTgkRSiTRTrJCKQwHqA'

management:
  security:
    enabled: false
